baseURL = "https://hex-go.github.io/"
title = "Hex Blog"
theme = "zzo"

languageCode = "en-us"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
# 统计中文字数
hasCJKLanguage = true
# 把 url 中的大写字符转为小写
disablePathToLower = false
# 把分类（categories）名称转为小写
preserveTaxonomyNames = false
# 取消默认的代码高亮，我们使用prism代码高亮
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsStyle = "dracula"
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = false
# 分页
paginate = 12
# 启用 Emoji; see emoji-cheat-sheet.com
enableEmoji = true

summaryLength = 70
buildFuture = true

copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
rssLimit = 100

enableGitInfo = false
googleAnalytics = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"