name: Publish Blog
run-name: ${{ github.actor }} is Publish Blog by GitHub Actions 🚀
on:
  # workflow_dispatch:
  push:
    branches:
    - hugo-src
jobs:
  Deploy-GitHub-Page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.110.0'
        extended: true

    - name: Build Hugo
      run:  hugo --minify --gc --cleanDestinationDir

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
        commit_message: ${{ github.event.head_commit.message }}